---
version: '3.7'
services:
  emq:
    image: emqx/emqx:latest
    ports:
      - 18083:18083
      - 1883:1883
      - 8081:8081
      - 8083:8083
      - 8883:8883
      - 8084:8084
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  hermes:
    build: ./
    image: hermes:latest
    depends_on:
      - emq
      - mongo
