---
{{- if .Values.ingress.enabled -}}
  {{- range .Values.ingress.hosts }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "hermes.fullname" $ }}-{{ .name }}
  labels:
    router: {{ .router }}
  {{- include "hermes.labels" $ | nindent 4 }}
spec:
  host: {{ .host | quote }}
  port:
    targetPort: {{ $.Values.service.port }}
  to:
    kind: Service
    name: {{ include "hermes.fullname" $ }}
    weight: 100
  wildcardPolicy: None
  {{- end }}
  {{- end }}
